markdown: kramdown
kramdown:
  parse_block_html: true
  toc_levels: 2..6
remote_theme: jekyll/minima
minima:
  skin: dark
header_pages:
  - README.md
author:
  name: Alister Scott
  email: "alister.scott@gmail.com"
plugins:
  - jekyll-feed
